trigger: 
- 'master'

variables:
  containerRegistry: 'My Hub'
  buildConfiguration: 'Release'
  leaderboardRepository: 'leaderboard'
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secret'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Docker@2
      displayName: 'Web docker'
      inputs:
        containerRegistry: $(containerRegistry)
        repository: '$(webRepository)'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: '$(tag)'
    - task: Docker@2
      displayName: 'Leaderboard docker'
      inputs:
        containerRegistry: $(containerRegistry)
        repository: '$(leaderboardRepository)'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.LeaderboardContainer/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: '$(tag)'
    - publish: '$(Build.SourcesDirectory)/manifests'
      artifact: manifests
- stage: 'Deploy'
  displayName: 'Deploy the containers'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-18.04'
    environment: 'AKS.space-game'
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps: