trigger: 
- 'master'

variables:
  containerRegistry: 'My Hub'
  buildConfiguration: 'Release'
  leaderboardRepository: 'luheorga/leaderboard'
  webRepository: 'luheorga/web'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secret'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Docker@2
      displayName: 'Web docker'
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(webRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: 'Leaderboard docker'
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(leaderboardRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(tag)
          latest
    - publish: '$(Build.SourcesDirectory)/manifests'
      artifact: manifests
- stage: 'Deploy'
  displayName: 'Deploy the containers'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-18.04'
    environment: 'AKS.space-game'
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: manifests
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: 'createSecret'
              kubernetesServiceConnection: 'NS space-game'
              namespace: 'space-game'
              secretType: 'dockerRegistry'
              secretName: '$(imagePullSecret)'
              dockerRegistryEndpoint: 'My Hub'
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'NS space-game'
              namespace: 'space-game'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              containers: |
                $(RegistryName)/$(webRepository):$(tag)
                $(RegistryName)/$(leaderboardRepository):$(tag)
              imagePullSecrets: '$(imagePullSecret)'